import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import CalendlyBadgeClient from "./components/CalendlyBadgeClient";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Calendly badge widget assets */}
        <link
          rel="stylesheet"
          href="https://assets.calendly.com/assets/external/widget.css"
        />
      </head>
      <body
        className={`${inter.variable} ${robotoMono.variable} antialiased`}
      >
        {children}
        {/* External Calendly script */}
        <Script id="calendly-external" src="https://assets.calendly.com/assets/external/widget.js" strategy="afterInteractive" />
        {/* Client component that initializes the badge after script becomes available */}
        <CalendlyBadgeClient />
      </body>
    </html>
  );
}
